### ISSUE TITLE
Migrate these to monarch-initiative org

### ISSUE THREAD

**Issue by nlharris** [tis-lab/closed-illustrations#2]
Shouldn't these be in the monarch-initiative org rather than Julie's private org? Is it a hassle to move them? I'm not a git guru, so I'm not sure how hard it would be.

**Comment by nlharris** [comment]
is this now moot? @jmcmurry

**Comment by jmcmurry** [comment]
this is where I put all the logos for all the projects and they span well beyond monarch, so while it is trivial to migrate them once to their respective destinations, it would be hard to figure out where all those destinations are when I need them

**Comment by sagehrke** [comment]
@jmcmurry I wonder if we could move this to TISlab's Org and then make it private. That way we can give access to editors, but it's still in a TISLab centric location to easily find for any TISLab project?

**Comment by sagehrke** [comment]
We've moved this repo to the TISLab org so it's a bit more accessible. This solves this issue.
